platform:ios,'8.0'
use_frameworks!

target 'Eyepetizer' do
  pod 'Alamofire'
  pod 'APESuperHUD'
  pod 'DeviceKit', '~> 0.3.2'
  pod 'JSAnimatedImagesView'
  pod 'R.swift'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'StarWars'
  pod 'XCGLogger', '~> 3.3'               # https://github.com/DaveWoodCom/XCGLogger
  pod 'YYWebImage'
end
